Repository MVP-Test-FinalProject/mvp-test, pull requests merged in 2024-07, with the labels that each got.

#5 Feat/#1 member enterprise
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/common/error/EnterpriseErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/MemberErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/team1/mvp_test/common/exception/ModelNotFoundException.kt
  src/main/kotlin/com/team1/mvp_test/common/exception/PasswordIncorrectException.kt
  src/main/kotlin/com/team1/mvp_test/common/exception/dto/ErrorResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/controller/EnterpriseController.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/dto/EnterpriseLoginResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/dto/EnterpriseResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/dto/EnterpriseSignUpRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/dto/LoginRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/dto/UpdateEnterpriseRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/model/Enterprise.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/repository/EnterpriseRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseService.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/controller/MemberController.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/LoginResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberUpdateRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberUpdateResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/SignUpRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Member.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/service/MemberService.kt
  src/main/kotlin/com/team1/mvp_test/infra/swagger/SwaggerConfig.kt
Labels: :sparkles: feat

#7 Feat/#6 enterprise login
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/common/Role.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/controller/EnterpriseController.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseAuthService.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseService.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/PasswordEncodeConfig.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/SecurityConfig.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/UserPrincipal.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/jwt/JwtHelper.kt
  src/main/kotlin/com/team1/mvp_test/infra/swagger/SwaggerConfig.kt
Labels: :sparkles: feat

#9 Feat/#8 member social login
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/controller/EnterpriseController.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/controller/MemberController.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberUpdateResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/SignUpRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Member.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/service/MemberService.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/client/OAuthClient.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/client/OAuthClientService.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/client/OAuthLoginUserInfo.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/client/naver/NaverOAuthClient.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/client/naver/dto/NaverOAuthUserInfo.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/client/naver/dto/NaverTokenResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/config/RestClientConfig.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/controller/MemberOAuthController.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/exception/InvalidOAuthUserException.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/exception/OAuthTokenRetrieveException.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/provider/OAuthProvider.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/provider/OAuthProviderConverter.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/service/OAuthLoginService.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/SecurityConfig.kt
Labels: :sparkles: feat

#15 Feat/#2 domain report
  src/main/kotlin/com/team1/mvp_test/common/error/MvpTestErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/ReportErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/team1/mvp_test/common/exception/NoPermissionException.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/MemberTest.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/controller/MvpTestController.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/mvptest/CreateMpvTestRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/mvptest/TestingMemberCountResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/Category.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/CategoryMap.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/controller/ReportController.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/ApproveReportRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/ApproveReportResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/ReportResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/UpdateReportRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/model/Report.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/model/ReportMedia.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/repository/ReportMediaRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/repository/ReportRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/model/Step.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/StepService.kt
Labels: :sparkles: feat

#22 Feat/#16 report validations
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/common/error/ReportErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/model/Report.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
Labels: :sparkles: feat

#23 Feat/#12 Implement Enterprise, Member validate
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/model/Enterprise.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Member.kt
Labels: :sparkles: feat

#27 Feat/#18 step validation
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/CreateStepRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/StepResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/UpdateStepRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/model/Step.kt
  src/test/kotlin/com/team1/mvp_test/step/StepServiceTest.kt
Labels: :sparkles: feat, :white_check_mark: test

#28 Feat/#25 report test code
  src/main/kotlin/com/team1/mvp_test/common/error/ReportErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/ReportResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/repository/ReportMediaRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/repository/ReportRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/ReportTest.kt
Labels: :white_check_mark: test

#29 Feat/#12 enterprise member test
  build.gradle.kts
  src/test/kotlin/com/team1/mvp_test/enterprise/EnterpriseAuthServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/member/MemberServiceTest.kt
Labels: :white_check_mark: test

#30 Feat/#17 mvptest domain entity validate
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTestTest.kt
Labels: :sparkles: feat, :white_check_mark: test

#31 Feat/#20 crud refactor
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/common/DatabaseInitializer.kt
  src/main/kotlin/com/team1/mvp_test/common/error/MvpTestErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/ReportErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/StepErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/exception/NoPermissionException.kt
  src/main/kotlin/com/team1/mvp_test/domain/category/dto/CreateCategoryRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/category/model/Category.kt
  src/main/kotlin/com/team1/mvp_test/domain/category/repository/CategoryRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/controller/EnterpriseController.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/model/Enterprise.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/model/EnterpriseState.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseService.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/controller/MemberController.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/SignUpInfoRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Member.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/MemberTest.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/MemberTestState.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/service/MemberService.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/constant/RecruitType.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/controller/MvpTestController.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/CreateMvpTestRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/MvpTestResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/UpdateMvpTestRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/mvptest/CreateCategoryRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/mvptest/CreateMpvTestRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/mvptest/MvpTestListResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/mvptest/TestingMemberCountResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/mvptest/UpdateMvpTestRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/CategoryMap.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/CategoryMapId.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTestCategoryMap.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTestState.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/RecruitType.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/repository/CategoryMapRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/repository/CategoryRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/repository/MvpTestCategoryMapRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/controller/ReportController.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/ApproveReportResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/ReportResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/UpdateReportRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/model/Report.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/model/ReportMedia.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/model/ReportState.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/repository/ReportRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/controller/StepController.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/StepListResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/StepResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/model/Step.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/repository/StepRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/StepService.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTestTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/ReportTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/service/ReportServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/member/MemberServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/step/StepServiceTest.kt
Labels: :recycle: refactor, :white_check_mark: test

#35 Feat/#32 dto validation
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/common/error/MvpTestErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/controller/EnterpriseController.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/dto/EnterpriseSignUpRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/dto/UpdateEnterpriseRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/model/Enterprise.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseService.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/controller/MemberController.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberUpdateRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberUpdateResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/SignUpInfoRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Member.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Sex.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/service/MemberService.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/controller/MvpTestController.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/CreateMvpTestRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/MvpTestResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/UpdateMvpTestRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/UpdateMvpTestObject.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/controller/ReportController.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/ReportRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/UpdateReportRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/model/Report.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/controller/StepController.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/CreateStepRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/UpdateStepRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/model/Step.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/StepService.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/SecurityConfig.kt
  src/test/kotlin/com/team1/mvp_test/domain/enterprise/EnterpriseAuthServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/enterprise/dto/EnterpriseDtoTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/member/MemberServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/member/dto/MemberDtoTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/dto/MvpTestDtoTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTestTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/dto/ReportDtoTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/service/ReportServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/dto/StepDtoTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepServiceTest.kt
Labels: :recycle: refactor, :white_check_mark: test

#37 HOTFIX: remove old tests
  src/test/kotlin/com/team1/mvp_test/domain/enterprise/EnterpriseAuthServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/member/MemberServiceTest.kt
Labels: :bug: fix

#40 Feat/#38 message verify
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/common/error/MemberErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/SignUpInfoRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Member.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/service/MemberService.kt
  src/main/kotlin/com/team1/mvp_test/domain/message/controller/MessageController.kt
  src/main/kotlin/com/team1/mvp_test/domain/message/service/MessageService.kt
  src/main/kotlin/com/team1/mvp_test/infra/redis/RedisConfig.kt
  src/main/kotlin/com/team1/mvp_test/infra/redis/RedisService.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/SecurityConfig.kt
  src/test/kotlin/com/team1/mvp_test/domain/member/dto/MemberDtoTest.kt
Labels: :sparkles: feat

#42 Feat/#34 s3 file
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/common/error/MvpTestErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/ReportErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/S3ErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/controller/MvpTestController.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/CreateMvpTestRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/UpdateMvpTestRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/controller/ReportController.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/ReportRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/controller/StepController.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/CreateStepRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/UpdateStepRequest.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/StepService.kt
  src/main/kotlin/com/team1/mvp_test/infra/s3/s3config/S3Config.kt
  src/main/kotlin/com/team1/mvp_test/infra/s3/s3service/S3Service.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/dto/MvpTestDtoTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/dto/ReportDtoTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/service/ReportServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/dto/StepDtoTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepServiceTest.kt
Labels: :sparkles: feat, :white_check_mark: test

#43 Feat/#39 admin api
  src/main/kotlin/com/team1/mvp_test/admin/controller/AdminController.kt
  src/main/kotlin/com/team1/mvp_test/admin/dto/AdminLoginRequest.kt
  src/main/kotlin/com/team1/mvp_test/admin/dto/AdminLoginResponse.kt
  src/main/kotlin/com/team1/mvp_test/admin/model/Admin.kt
  src/main/kotlin/com/team1/mvp_test/admin/repository/AdminRepository.kt
  src/main/kotlin/com/team1/mvp_test/admin/service/AdminAuthService.kt
  src/main/kotlin/com/team1/mvp_test/admin/service/AdminService.kt
  src/main/kotlin/com/team1/mvp_test/common/DatabaseInitializer.kt
  src/main/kotlin/com/team1/mvp_test/common/error/EnterpriseErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/MemberErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/dto/EnterpriseResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/model/Enterprise.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseAuthService.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseService.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Member.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/MemberState.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/service/MemberService.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/main/kotlin/com/team1/mvp_test/infra/security/SecurityConfig.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/service/ReportServiceTest.kt
Labels: :sparkles: feat

#45 HOTFIX #issue 44
  src/main/kotlin/com/team1/mvp_test/infra/s3/s3service/S3Service.kt
Labels: :bug: fix

#48 Feat/#33 mvptest apply.concurrency
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/main/kotlin/com/team1/mvp_test/infra/redisson/RedissonConfig.kt
  src/main/kotlin/com/team1/mvp_test/infra/redisson/RedissonService.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/apply/ConcurrencyControl.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/apply/RedissonTestConfig.kt
  src/test/resources/redisson.yml
Labels: :sparkles: feat, :white_check_mark: test

#50 Feat/#36 ci pipeline
  .github/workflows/gradle.yml
Labels: :sparkles: feat

#51 Feat/#47 reward batch process
  .github/workflows/gradle.yml
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/admin/controller/AdminController.kt
  src/main/kotlin/com/team1/mvp_test/admin/service/AdminService.kt
  src/main/kotlin/com/team1/mvp_test/batch/model/BatchData.kt
  src/main/kotlin/com/team1/mvp_test/batch/model/BatchJobData.kt
  src/main/kotlin/com/team1/mvp_test/batch/model/BatchStatus.kt
  src/main/kotlin/com/team1/mvp_test/batch/repository/BatchDataRepository.kt
  src/main/kotlin/com/team1/mvp_test/batch/repository/BatchJobDataRepository.kt
  src/main/kotlin/com/team1/mvp_test/batch/service/BatchService.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Member.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/repository/MvpTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/repository/ReportRepository.kt
  src/main/kotlin/com/team1/mvp_test/infra/querydsl/QueryDslConfig.kt
  src/test/kotlin/com/team1/mvp_test/MvpTestApplicationTests.kt
  src/test/kotlin/com/team1/mvp_test/batch/BatchServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/apply/ConcurrencyControl.kt
  src/test/resources/application-test.yml
Labels: :sparkles: feat, :white_check_mark: test
