Repository MVP-Test-FinalProject/mvp-test, pull requests merged in 2024-08, with the labels that each got.

#54 Feat/#49 mvp test check condition
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/common/error/MvpTestErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/main/kotlin/com/team1/mvp_test/infra/redisson/RedissonService.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/apply/ConcurrencyControl.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/apply/RedissonTestConfig.kt
  src/test/resources/redisson.yml
Labels: :sparkles: feat, :white_check_mark: test

#58 53 docker image 빌드
  .github/workflows/gradle.yml
  Dockerfile
Labels: :sparkles: feat

#59 Feat/#56 admin
  src/main/kotlin/com/team1/mvp_test/admin/controller/AdminController.kt
  src/main/kotlin/com/team1/mvp_test/admin/controller/AdminRoleController.kt
  src/main/kotlin/com/team1/mvp_test/admin/dto/adminauthority/MvpTestListResponse.kt
  src/main/kotlin/com/team1/mvp_test/admin/dto/adminauthority/RejectRequest.kt
  src/main/kotlin/com/team1/mvp_test/admin/service/AdminService.kt
  src/main/kotlin/com/team1/mvp_test/common/error/AdminErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/CategoryErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/EnterpriseErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/MemberErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/MvpTestErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/common/error/StepErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/domain/category/controller/CategoryController.kt
  src/main/kotlin/com/team1/mvp_test/domain/category/service/CategoryService.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/model/Enterprise.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseAuthService.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseService.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/Member.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/controller/MvpTestController.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/controller/ReportController.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/controller/StepController.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/StepService.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/apply/ConcurrencyControl.kt
Labels: :sparkles: feat, :recycle: refactor

#60 Feat/#57 step check reports
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/domain/report/model/ReportState.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/repository/ReportRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/controller/StepController.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/ReportStatusResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/StepOverviewResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/StepService.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepServiceTest.kt
Labels: :sparkles: feat

#62 Feat/#61 mvpTest domain API Implement
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/controller/MvpTestController.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/MemberInfoResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/repository/MvpTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
Labels: :sparkles: feat

#63 Feat/#57 step check reports
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/MemberReportService.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/StepService.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepIntegrationTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepTestConfig.kt
Labels: :recycle: refactor, :white_check_mark: test

#67 Feat/#64 mvptest get available tests
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/controller/MvpTestController.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/repository/MvpTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestIntegrationTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestTestConfig.kt
Labels: :sparkles: feat, :white_check_mark: test

#71 Feat/#69 s3 service
  .github/workflows/gradle.yml
  src/main/kotlin/com/team1/mvp_test/common/error/S3ErrorMessage.kt
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/model/Enterprise.kt
  src/main/kotlin/com/team1/mvp_test/infra/s3/s3service/S3Service.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/service/ReportServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepServiceTest.kt
Labels: :bug: fix, :recycle: refactor

#73 Feat/#65 mvp tests service test
  src/main/kotlin/com/team1/mvp_test/domain/enterprise/model/Enterprise.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestServiceTest.kt
Labels: :white_check_mark: test

#74 Feat/#72 enterprise service test
  src/test/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseAuthServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/enterprise/service/EnterpriseServiceTest.kt
Labels: :white_check_mark: test

#75 Test/#68 member service test code
  src/main/kotlin/com/team1/mvp_test/domain/member/service/MemberService.kt
  src/test/kotlin/com/team1/mvp_test/domain/member/service/MemberServiceUnitTest.kt
Labels: :white_check_mark: test

#79 Feat/#76 batch refactor
  src/main/kotlin/com/team1/mvp_test/admin/controller/AdminController.kt
  src/main/kotlin/com/team1/mvp_test/admin/service/AdminService.kt
  src/main/kotlin/com/team1/mvp_test/batch/Job.kt
  src/main/kotlin/com/team1/mvp_test/batch/Step.kt
  src/main/kotlin/com/team1/mvp_test/batch/exception/BatchJobAlreadyDoneException.kt
  src/main/kotlin/com/team1/mvp_test/batch/model/BatchData.kt
  src/main/kotlin/com/team1/mvp_test/batch/model/BatchJobData.kt
  src/main/kotlin/com/team1/mvp_test/batch/model/BatchJobExecution.kt
  src/main/kotlin/com/team1/mvp_test/batch/model/BatchJobInstance.kt
  src/main/kotlin/com/team1/mvp_test/batch/model/BatchStatus.kt
  src/main/kotlin/com/team1/mvp_test/batch/model/BatchStepExecution.kt
  src/main/kotlin/com/team1/mvp_test/batch/repository/BatchDataRepository.kt
  src/main/kotlin/com/team1/mvp_test/batch/repository/BatchJobDataRepository.kt
  src/main/kotlin/com/team1/mvp_test/batch/repository/BatchJobExecutionRepository.kt
  src/main/kotlin/com/team1/mvp_test/batch/repository/BatchJobInstanceRepository.kt
  src/main/kotlin/com/team1/mvp_test/batch/repository/BatchStepExecutionRepository.kt
  src/main/kotlin/com/team1/mvp_test/batch/reward/CreateSettlementDataStep.kt
  src/main/kotlin/com/team1/mvp_test/batch/reward/PayMemberRewardStep.kt
  src/main/kotlin/com/team1/mvp_test/batch/reward/RewardSettlementJob.kt
  src/main/kotlin/com/team1/mvp_test/batch/service/BatchService.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/model/MemberReward.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberRewardRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/model/MvpTest.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/repository/MvpTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/repository/ReportRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/settlement/Settlement.kt
  src/main/kotlin/com/team1/mvp_test/domain/settlement/SettlementRepository.kt
  src/test/kotlin/com/team1/mvp_test/domain/batch/RewardSettlementJobFailTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/batch/RewardSettlementJobIntegrateTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/batch/RewardSettlementJobUnitTest.kt
  src/test/resources/application-test.yml
Labels: :recycle: refactor, :white_check_mark: test

#81 feat/#80 s3Service
  build.gradle.kts
  src/main/kotlin/com/team1/mvp_test/common/DatabaseInitializer.kt
  src/main/kotlin/com/team1/mvp_test/infra/s3/s3service/S3Service.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/mvptest/service/apply/RedissonTestConfig.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/service/ReportServiceTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepServiceTest.kt
Labels: :sparkles: feat, :white_check_mark: test

#87 Feat/86 Update CreateMvpTestRequest
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/CreateMvpTestRequest.kt
Labels: :bug: fix

#89 Feat/88 Update MvpTestResponse
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/dto/MvpTestResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
Labels: :bug: fix

#93 Feat/92 Update Member LoginResponse to return member's state
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/LoginResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/oauth/service/OAuthLoginService.kt
Labels: :bug: fix

#95 Feat/94 Update verifyCode API response as Json
  src/main/kotlin/com/team1/mvp_test/domain/message/VerifyCodeResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/message/controller/MessageController.kt
  src/main/kotlin/com/team1/mvp_test/domain/message/service/MessageService.kt
Labels: :bug: fix

#97 Feat/96 Update getStepList API authorization scope
  src/main/kotlin/com/team1/mvp_test/domain/step/controller/StepController.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/StepService.kt
Labels: :bug: fix

#99 Feat/98 Update requirementSex check logic
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
Labels: :bug: fix

#101 Feat/100 Implement Get MvpTest API for member
  src/main/kotlin/com/team1/mvp_test/admin/service/AdminService.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/controller/MemberController.kt
  src/main/kotlin/com/team1/mvp_test/domain/member/repository/MemberTestRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/mvptest/service/MvpTestService.kt
Labels: :sparkles: feat

#103 Feat/102 Implement Member Profile api
  src/main/kotlin/com/team1/mvp_test/domain/member/controller/MemberController.kt
Labels: :sparkles: feat

#105 Feat/#104 member report get api
  src/main/kotlin/com/team1/mvp_test/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/controller/ReportController.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/dto/ReportResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/repository/ReportRepository.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/controller/StepController.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/dto/StepListResponse.kt
  src/main/kotlin/com/team1/mvp_test/domain/step/service/StepService.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepIntegrationTest.kt
  src/test/kotlin/com/team1/mvp_test/domain/step/service/StepServiceTest.kt
Labels: :sparkles: feat

#107 Feat/#106 s3Service
  src/main/kotlin/com/team1/mvp_test/domain/report/controller/ReportController.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
  src/main/kotlin/com/team1/mvp_test/infra/s3/s3service/S3Service.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/service/ReportServiceTest.kt
Labels: :recycle: refactor

#109 Feat/#108 reportServiceTest code
  src/test/kotlin/com/team1/mvp_test/domain/report/service/ReportServiceTest.kt
Labels: :recycle: refactor

#113 Feat/#112 batch scheduler
  src/main/kotlin/com/team1/mvp_test/MvpTestApplication.kt
  src/main/kotlin/com/team1/mvp_test/batch/BatchScheduler.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/model/Report.kt
  src/main/kotlin/com/team1/mvp_test/domain/report/service/ReportService.kt
  src/test/kotlin/com/team1/mvp_test/domain/report/service/ReportServiceTest.kt
Labels: :bug: fix, :sparkles: feat
